name: Deploy Backend to DigitalOcean

on:
  push:
    branches:
      - main  # Runs this workflow when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to DigitalOcean via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/mern_app/server

            # Ensure the repository is up-to-date
            git pull origin main

            # Install dependencies
            npm install --production

            # Update the .env file
            echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" > .env

            # Restart the backend with PM2
            pm2 restart all

            # Optional: Save PM2 process list so it auto-starts on reboot
            pm2 save
