name: Deploy Backend to DigitalOcean

on:
  push:
    branches:
      - main  # Runs this workflow when pushing to the main branch
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to DigitalOcean via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: |
            ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/mern_app/server

            # Pull latest changes
            git pull origin main

            # Install dependencies (production-only)
            npm install --production

            # Write .env from GitHub Secrets
            echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" > .env

            # Restart backend with PM2
            pm2 restart all

            # Save PM2 process list to auto-start on reboot
            pm2 save
